train epoch:1:   0%|                                                                                                                                                                  | 0/20227 [00:00<?, ?it/s]/home/yilin/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/nn/modules/loss.py:97: UserWarning: Using a target size (torch.Size([16, 1, 3000])) that is different to the input size (torch.Size([16, 3000])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(input, target, reduction=self.reduction)














train epoch:1:   0%|                                                                                                                                                      | 15/20227 [01:02<23:17:26,  4.15s/it]
Traceback (most recent call last):
  File "traineval.py", line 63, in <module>
    train_val(trainloader, valloader, testloader)
  File "traineval.py", line 24, in train_val
    checkpoints = trainer.epoch(epoch + 1)
  File "/home/datassd/yilin/Codes/Hand/ConditionHOI/epochbase.py", line 244, in epoch
    self.one_batch(sample)
  File "/home/datassd/yilin/Codes/Hand/ConditionHOI/epochbase.py", line 198, in one_batch
    self.model_update(dict_losses)
  File "/home/datassd/yilin/Codes/Hand/ConditionHOI/epochbase.py", line 171, in model_update
    dict_losses['total_loss_cond'].backward()
  File "/home/yilin/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/yilin/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
KeyboardInterrupt